# uses aws/codebuild/nodejs:8.11.0
#
version: 0.2

env:
  variables:
    WEB_BUCKET1: "cliffanalysis.com"


phases:

  install:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 cp --recursive --acl public-read ./build s3://cliffanalysis.com/
      - echo $WEB_BUCKET
      - echo $WEB_BUCKET1



artifacts:
  files:
    - "**/*"
  base-directory: build
