# uses aws/codebuild/nodejs:8.11.0
#
version: 0.1

phases:

  install:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 cp --recursive --acl public-read ./build s3://$WEB_BUCKET/



artifacts:
  files:
    - "**/*"
  base-directory: build
