# uses aws/codebuild/nodejs:8.11.0
#
# this will run `npm run build` and sync the output to S3
#
version: 0.2


phases:

  install:
    commands:
      - npm install
      - aws cloudformation update-stack --stack-name $STACK_NAME --template-body file://base-cfn.json
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 sync ./build s3://$WEB_BUCKET/ --delete --acl public-read

artifacts:
  files:
    - "**/*"
  base-directory: build
