# uses aws/codebuild/nodejs:8.11.0
# cliff consulting build spec# this will run `npm run build` and sync the output to S3
#
version: 0.2

# sourced from CodeBuild project
#env:
  #variables:
    #STACK_NAME: "cliffconsulting-develop"
    #WEB_BUCKET: <from CodeBuild project>

phases:

  install:
    commands:
      # no stack update currently returns 255 status code
      #  updated to 1.16 awscli to resolve
      - id
      #- pip install --upgrade --user awscli
      - aws --version
      - echo $STACK_NAME
      - |
        aws cloudformation validate-template \
            --template-body file://base-cfn.json
      # this is to check if any changes first
      - |
        aws cloudformation create-change-set \
            --stack-name $STACK_NAME \
            --change-set-name ci-test-if-changes \
            --template-body file://base-cfn.json \
            --capabilities CAPABILITY_IAM \
            --parameters ParameterKey=WebHostName,UsePreviousValue=true
      - |
        CHANGE_SET=$(aws cloudformation describe-change-set \
            --stack-name $STACK_NAME \
            --change-set-name ci-test-if-changes | \
                jq -r '.Changes[]')
      - |
        aws cloudformation delete-change-set \
            --stack-name $STACK_NAME \
            --change-set-name ci-test-if-changes
      - echo $CHANGE_SET
      - |
        if [ -z $CHANGE_SET ]
        then
          aws cloudformation update-stack \
              --stack-name $STACK_NAME \
              --template-body file://base-cfn.json \
              --capabilities CAPABILITY_IAM \
              --parameters ParameterKey=WebHostName,UsePreviousValue=true
        fi
      - npm install
  #pre_build:
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 sync ./build s3://$WEB_BUCKET/ --delete --acl public-read

artifacts:
  files:
    - "**/*"
  base-directory: build

# cache:
#   paths:
#     - ?? npm install stuff?
