# uses aws/codebuild/nodejs:8.11.0
# cliff consulting build spec# this will run `npm run build` and sync the output to S3
#
version: 0.2

# sourced from CodeBuild project
#env:
  #variables:
    #STACK_NAME: "cliffconsulting-develop"
    #WEB_BUCKET: <from CodeBuild project>

phases:

  install:
    commands:
      - aws --version
      - echo $STACK_NAME
      # no stack update currently returns 255 status code
      #  the exit 0 at the end swallows this
      - |
        aws cloudformation update-stack \
            --stack-name $STACK_NAME \
            --template-body file://base-cfn.json \
            --capabilities CAPABILITY_IAM \
            --parameters ParameterKey=WebHostName,UsePreviousValue=true \
            || exit 0
      - npm install
  #pre_build:
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 sync ./build s3://$WEB_BUCKET/ --delete --acl public-read

artifacts:
  files:
    - "**/*"
  base-directory: build

# cache:
#   paths:
#     - ?? npm install stuff?
